### ISSUE TITLE
Test failing, even though no examples are given

### ISSUE THREAD

**Issue by brianamarie** [phantompower/checkit#6]
Hello! I'd love some help troubleshooting an interesting behavior. 

- [Pull request](https://github.com/github/training-kit/pull/473)
- [Most recent log output from Travis](https://travis-ci.org/github/training-kit/builds/202422136)

Snapshot of how this looks at the tail of the log:
<img width="539" alt="screen shot 2017-02-16 at 4 23 28 pm" src="https://cloud.githubusercontent.com/assets/9906718/23044088/509dfb16-f464-11e6-968b-ce17e403029d.png">

@phantompower Do you have any ideas for why this is failing, even though there are no examples being shown? 

cc @stoe

**Comment by phantompower** [comment]
I would say that is a permission issue.  You might install from NPM?
https://www.npmjs.com/package/writewell
